/**
 * podravka.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.2.3-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Podravkaio) {
      root.Podravkaio = {};
    }
    root.Podravkaio.AttributeDefinitionCreate = factory(root.Podravkaio.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The AttributeDefinitionCreate model module.
   * @module model/AttributeDefinitionCreate
   * @version 0.2.0
   */

  /**
   * Constructs a new <code>AttributeDefinitionCreate</code>.
   * Class AttributeDefinition.
   * @alias module:model/AttributeDefinitionCreate
   * @class
   * @param scope {module:model/AttributeDefinitionCreate.ScopeEnum} 
   * @param name {String} 
   * @param type {module:model/AttributeDefinitionCreate.TypeEnum} 
   */
  var exports = function(scope, name, type) {
    var _this = this;

    _this['scope'] = scope;
    _this['name'] = name;
    _this['type'] = type;

  };

  /**
   * Constructs a <code>AttributeDefinitionCreate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AttributeDefinitionCreate} obj Optional instance to populate.
   * @return {module:model/AttributeDefinitionCreate} The populated <code>AttributeDefinitionCreate</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('scope')) {
        obj['scope'] = ApiClient.convertToType(data['scope'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('required')) {
        obj['required'] = ApiClient.convertToType(data['required'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/AttributeDefinitionCreate.ScopeEnum} scope
   */
  exports.prototype['scope'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {module:model/AttributeDefinitionCreate.TypeEnum} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {Boolean} required
   * @default false
   */
  exports.prototype['required'] = false;


  /**
   * Allowed values for the <code>scope</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ScopeEnum = {
    /**
     * value: "client"
     * @const
     */
    "client": "client",
    /**
     * value: "client+user"
     * @const
     */
    "client+user": "client+user"  };

  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "array"
     * @const
     */
    "array": "array",
    /**
     * value: "boolean"
     * @const
     */
    "boolean": "boolean",
    /**
     * value: "numeric"
     * @const
     */
    "numeric": "numeric",
    /**
     * value: "reference"
     * @const
     */
    "reference": "reference",
    /**
     * value: "string"
     * @const
     */
    "string": "string"  };


  return exports;
}));


