/**
 * podravka.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.2.3-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ImageInstanceEmbed'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ImageInstanceEmbed'));
  } else {
    // Browser globals (root is window)
    if (!root.Podravkaio) {
      root.Podravkaio = {};
    }
    root.Podravkaio.ImageVariationUrlVarsEmbed = factory(root.Podravkaio.ApiClient, root.Podravkaio.ImageInstanceEmbed);
  }
}(this, function(ApiClient, ImageInstanceEmbed) {
  'use strict';




  /**
   * The ImageVariationUrlVarsEmbed model module.
   * @module model/ImageVariationUrlVarsEmbed
   * @version 0.2.0
   */

  /**
   * Constructs a new <code>ImageVariationUrlVarsEmbed</code>.
   * Image variation url vars.
   * @alias module:model/ImageVariationUrlVarsEmbed
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>ImageVariationUrlVarsEmbed</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ImageVariationUrlVarsEmbed} obj Optional instance to populate.
   * @return {module:model/ImageVariationUrlVarsEmbed} The populated <code>ImageVariationUrlVarsEmbed</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('instance')) {
        obj['instance'] = ApiClient.convertToType(data['instance'], [ImageInstanceEmbed]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/ImageInstanceEmbed>} instance
   */
  exports.prototype['instance'] = undefined;



  return exports;
}));


