/**
 * podravka.io
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ImageVariationUrlVarsImageRead'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ImageVariationUrlVarsImageRead'));
  } else {
    // Browser globals (root is window)
    if (!root.Podravkaio) {
      root.Podravkaio = {};
    }
    root.Podravkaio.ImageVariationImageRead = factory(root.Podravkaio.ApiClient, root.Podravkaio.ImageVariationUrlVarsImageRead);
  }
}(this, function(ApiClient, ImageVariationUrlVarsImageRead) {
  'use strict';




  /**
   * The ImageVariationImageRead model module.
   * @module model/ImageVariationImageRead
   * @version 0.0.2
   */

  /**
   * Constructs a new <code>ImageVariationImageRead</code>.
   * Image variation.
   * @alias module:model/ImageVariationImageRead
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ImageVariationImageRead</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ImageVariationImageRead} obj Optional instance to populate.
   * @return {module:model/ImageVariationImageRead} The populated <code>ImageVariationImageRead</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('url_template')) {
        obj['url_template'] = ApiClient.convertToType(data['url_template'], 'String');
      }
      if (data.hasOwnProperty('url_vars')) {
        obj['url_vars'] = ImageVariationUrlVarsImageRead.constructFromObject(data['url_vars']);
      }
    }
    return obj;
  }

  /**
   * @member {String} url_template
   */
  exports.prototype['url_template'] = undefined;
  /**
   * @member {module:model/ImageVariationUrlVarsImageRead} url_vars
   */
  exports.prototype['url_vars'] = undefined;



  return exports;
}));


