/**
 * podravka.io
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ImageInstanceImageRead'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ImageInstanceImageRead'));
  } else {
    // Browser globals (root is window)
    if (!root.Podravkaio) {
      root.Podravkaio = {};
    }
    root.Podravkaio.ImageVariationUrlVarsImageRead = factory(root.Podravkaio.ApiClient, root.Podravkaio.ImageInstanceImageRead);
  }
}(this, function(ApiClient, ImageInstanceImageRead) {
  'use strict';




  /**
   * The ImageVariationUrlVarsImageRead model module.
   * @module model/ImageVariationUrlVarsImageRead
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>ImageVariationUrlVarsImageRead</code>.
   * Image variation url vars.
   * @alias module:model/ImageVariationUrlVarsImageRead
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>ImageVariationUrlVarsImageRead</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ImageVariationUrlVarsImageRead} obj Optional instance to populate.
   * @return {module:model/ImageVariationUrlVarsImageRead} The populated <code>ImageVariationUrlVarsImageRead</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('instance')) {
        obj['instance'] = ApiClient.convertToType(data['instance'], [ImageInstanceImageRead]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/ImageInstanceImageRead>} instance
   */
  exports.prototype['instance'] = undefined;



  return exports;
}));


