/**
 * podravka.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.2.3-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ImageEmbed', 'model/NutritionDeclarationEmbed', 'model/UserEmbed'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ImageEmbed'), require('./NutritionDeclarationEmbed'), require('./UserEmbed'));
  } else {
    // Browser globals (root is window)
    if (!root.Podravkaio) {
      root.Podravkaio = {};
    }
    root.Podravkaio.IngredientRead = factory(root.Podravkaio.ApiClient, root.Podravkaio.ImageEmbed, root.Podravkaio.NutritionDeclarationEmbed, root.Podravkaio.UserEmbed);
  }
}(this, function(ApiClient, ImageEmbed, NutritionDeclarationEmbed, UserEmbed) {
  'use strict';




  /**
   * The IngredientRead model module.
   * @module model/IngredientRead
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>IngredientRead</code>.
   * Ingredient.
   * @alias module:model/IngredientRead
   * @class
   */
  var exports = function() {
    var _this = this;



















  };

  /**
   * Constructs a <code>IngredientRead</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IngredientRead} obj Optional instance to populate.
   * @return {module:model/IngredientRead} The populated <code>IngredientRead</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('state')) {
        obj['state'] = ApiClient.convertToType(data['state'], 'String');
      }
      if (data.hasOwnProperty('image')) {
        obj['image'] = ImageEmbed.constructFromObject(data['image']);
      }
      if (data.hasOwnProperty('name_english')) {
        obj['name_english'] = ApiClient.convertToType(data['name_english'], 'String');
      }
      if (data.hasOwnProperty('name_latin')) {
        obj['name_latin'] = ApiClient.convertToType(data['name_latin'], 'String');
      }
      if (data.hasOwnProperty('name_regional')) {
        obj['name_regional'] = ApiClient.convertToType(data['name_regional'], 'String');
      }
      if (data.hasOwnProperty('teaser')) {
        obj['teaser'] = ApiClient.convertToType(data['teaser'], 'String');
      }
      if (data.hasOwnProperty('lead')) {
        obj['lead'] = ApiClient.convertToType(data['lead'], 'String');
      }
      if (data.hasOwnProperty('content')) {
        obj['content'] = ApiClient.convertToType(data['content'], 'String');
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
      }
      if (data.hasOwnProperty('created_by')) {
        obj['created_by'] = UserEmbed.constructFromObject(data['created_by']);
      }
      if (data.hasOwnProperty('updated_at')) {
        obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
      }
      if (data.hasOwnProperty('updated_by')) {
        obj['updated_by'] = UserEmbed.constructFromObject(data['updated_by']);
      }
      if (data.hasOwnProperty('publish_requested_at')) {
        obj['publish_requested_at'] = ApiClient.convertToType(data['publish_requested_at'], 'Date');
      }
      if (data.hasOwnProperty('publish_requested_by')) {
        obj['publish_requested_by'] = UserEmbed.constructFromObject(data['publish_requested_by']);
      }
      if (data.hasOwnProperty('published_at')) {
        obj['published_at'] = ApiClient.convertToType(data['published_at'], 'Date');
      }
      if (data.hasOwnProperty('nutrition_declaration')) {
        obj['nutrition_declaration'] = NutritionDeclarationEmbed.constructFromObject(data['nutrition_declaration']);
      }
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} state
   */
  exports.prototype['state'] = undefined;
  /**
   * @member {module:model/ImageEmbed} image
   */
  exports.prototype['image'] = undefined;
  /**
   * @member {String} name_english
   */
  exports.prototype['name_english'] = undefined;
  /**
   * @member {String} name_latin
   */
  exports.prototype['name_latin'] = undefined;
  /**
   * @member {String} name_regional
   */
  exports.prototype['name_regional'] = undefined;
  /**
   * @member {String} teaser
   */
  exports.prototype['teaser'] = undefined;
  /**
   * @member {String} lead
   */
  exports.prototype['lead'] = undefined;
  /**
   * @member {String} content
   */
  exports.prototype['content'] = undefined;
  /**
   * @member {Date} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * @member {module:model/UserEmbed} created_by
   */
  exports.prototype['created_by'] = undefined;
  /**
   * @member {Date} updated_at
   */
  exports.prototype['updated_at'] = undefined;
  /**
   * @member {module:model/UserEmbed} updated_by
   */
  exports.prototype['updated_by'] = undefined;
  /**
   * @member {Date} publish_requested_at
   */
  exports.prototype['publish_requested_at'] = undefined;
  /**
   * @member {module:model/UserEmbed} publish_requested_by
   */
  exports.prototype['publish_requested_by'] = undefined;
  /**
   * @member {Date} published_at
   */
  exports.prototype['published_at'] = undefined;
  /**
   * @member {module:model/NutritionDeclarationEmbed} nutrition_declaration
   */
  exports.prototype['nutrition_declaration'] = undefined;



  return exports;
}));


