/**
 * podravka.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.2.3-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/NutritionDeclarationEmbedBase', 'model/NutritionDeclarationEmbedNutrients'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./NutritionDeclarationEmbedBase'), require('./NutritionDeclarationEmbedNutrients'));
  } else {
    // Browser globals (root is window)
    if (!root.Podravkaio) {
      root.Podravkaio = {};
    }
    root.Podravkaio.NutritionDeclarationEmbed = factory(root.Podravkaio.ApiClient, root.Podravkaio.NutritionDeclarationEmbedBase, root.Podravkaio.NutritionDeclarationEmbedNutrients);
  }
}(this, function(ApiClient, NutritionDeclarationEmbedBase, NutritionDeclarationEmbedNutrients) {
  'use strict';




  /**
   * The NutritionDeclarationEmbed model module.
   * @module model/NutritionDeclarationEmbed
   * @version 0.2.0
   */

  /**
   * Constructs a new <code>NutritionDeclarationEmbed</code>.
   * NutritionDeclaration.
   * @alias module:model/NutritionDeclarationEmbed
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>NutritionDeclarationEmbed</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NutritionDeclarationEmbed} obj Optional instance to populate.
   * @return {module:model/NutritionDeclarationEmbed} The populated <code>NutritionDeclarationEmbed</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('base')) {
        obj['base'] = NutritionDeclarationEmbedBase.constructFromObject(data['base']);
      }
      if (data.hasOwnProperty('energy')) {
        obj['energy'] = ApiClient.convertToType(data['energy'], [NutritionDeclarationEmbedBase]);
      }
      if (data.hasOwnProperty('nutrients')) {
        obj['nutrients'] = ApiClient.convertToType(data['nutrients'], [NutritionDeclarationEmbedNutrients]);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/NutritionDeclarationEmbedBase} base
   */
  exports.prototype['base'] = undefined;
  /**
   * @member {Array.<module:model/NutritionDeclarationEmbedBase>} energy
   */
  exports.prototype['energy'] = undefined;
  /**
   * @member {Array.<module:model/NutritionDeclarationEmbedNutrients>} nutrients
   */
  exports.prototype['nutrients'] = undefined;



  return exports;
}));


