/**
 * podravka.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.2.3-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BrandRead', 'model/ImageEmbed', 'model/NutritionDeclarationEmbed', 'model/UserEmbed'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BrandRead'), require('./ImageEmbed'), require('./NutritionDeclarationEmbed'), require('./UserEmbed'));
  } else {
    // Browser globals (root is window)
    if (!root.Podravkaio) {
      root.Podravkaio = {};
    }
    root.Podravkaio.ProductRead = factory(root.Podravkaio.ApiClient, root.Podravkaio.BrandRead, root.Podravkaio.ImageEmbed, root.Podravkaio.NutritionDeclarationEmbed, root.Podravkaio.UserEmbed);
  }
}(this, function(ApiClient, BrandRead, ImageEmbed, NutritionDeclarationEmbed, UserEmbed) {
  'use strict';




  /**
   * The ProductRead model module.
   * @module model/ProductRead
   * @version 0.2.0
   */

  /**
   * Constructs a new <code>ProductRead</code>.
   * Product.
   * @alias module:model/ProductRead
   * @class
   */
  var exports = function() {
    var _this = this;

























  };

  /**
   * Constructs a <code>ProductRead</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductRead} obj Optional instance to populate.
   * @return {module:model/ProductRead} The populated <code>ProductRead</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('state')) {
        obj['state'] = ApiClient.convertToType(data['state'], 'String');
      }
      if (data.hasOwnProperty('image')) {
        obj['image'] = ImageEmbed.constructFromObject(data['image']);
      }
      if (data.hasOwnProperty('brand')) {
        obj['brand'] = BrandRead.constructFromObject(data['brand']);
      }
      if (data.hasOwnProperty('lead')) {
        obj['lead'] = ApiClient.convertToType(data['lead'], 'String');
      }
      if (data.hasOwnProperty('claim')) {
        obj['claim'] = ApiClient.convertToType(data['claim'], 'String');
      }
      if (data.hasOwnProperty('preparation')) {
        obj['preparation'] = ApiClient.convertToType(data['preparation'], 'String');
      }
      if (data.hasOwnProperty('nutritional_facts')) {
        obj['nutritional_facts'] = ApiClient.convertToType(data['nutritional_facts'], 'String');
      }
      if (data.hasOwnProperty('storage_instructions')) {
        obj['storage_instructions'] = ApiClient.convertToType(data['storage_instructions'], 'String');
      }
      if (data.hasOwnProperty('shelf_life')) {
        obj['shelf_life'] = ApiClient.convertToType(data['shelf_life'], 'String');
      }
      if (data.hasOwnProperty('body')) {
        obj['body'] = ApiClient.convertToType(data['body'], 'String');
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
      }
      if (data.hasOwnProperty('created_by')) {
        obj['created_by'] = UserEmbed.constructFromObject(data['created_by']);
      }
      if (data.hasOwnProperty('updated_at')) {
        obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
      }
      if (data.hasOwnProperty('updated_by')) {
        obj['updated_by'] = UserEmbed.constructFromObject(data['updated_by']);
      }
      if (data.hasOwnProperty('publish_requested_at')) {
        obj['publish_requested_at'] = ApiClient.convertToType(data['publish_requested_at'], 'Date');
      }
      if (data.hasOwnProperty('publish_requested_by')) {
        obj['publish_requested_by'] = UserEmbed.constructFromObject(data['publish_requested_by']);
      }
      if (data.hasOwnProperty('published_start')) {
        obj['published_start'] = ApiClient.convertToType(data['published_start'], 'Date');
      }
      if (data.hasOwnProperty('published_end')) {
        obj['published_end'] = ApiClient.convertToType(data['published_end'], 'Date');
      }
      if (data.hasOwnProperty('launched_at')) {
        obj['launched_at'] = ApiClient.convertToType(data['launched_at'], 'Date');
      }
      if (data.hasOwnProperty('images')) {
        obj['images'] = ApiClient.convertToType(data['images'], [ImageEmbed]);
      }
      if (data.hasOwnProperty('nutrition_declaration')) {
        obj['nutrition_declaration'] = NutritionDeclarationEmbed.constructFromObject(data['nutrition_declaration']);
      }
      if (data.hasOwnProperty('extended_attributes')) {
        obj['extended_attributes'] = ApiClient.convertToType(data['extended_attributes'], Object);
      }
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * @member {String} state
   */
  exports.prototype['state'] = undefined;
  /**
   * @member {module:model/ImageEmbed} image
   */
  exports.prototype['image'] = undefined;
  /**
   * @member {module:model/BrandRead} brand
   */
  exports.prototype['brand'] = undefined;
  /**
   * @member {String} lead
   */
  exports.prototype['lead'] = undefined;
  /**
   * @member {String} claim
   */
  exports.prototype['claim'] = undefined;
  /**
   * @member {String} preparation
   */
  exports.prototype['preparation'] = undefined;
  /**
   * @member {String} nutritional_facts
   */
  exports.prototype['nutritional_facts'] = undefined;
  /**
   * @member {String} storage_instructions
   */
  exports.prototype['storage_instructions'] = undefined;
  /**
   * @member {String} shelf_life
   */
  exports.prototype['shelf_life'] = undefined;
  /**
   * @member {String} body
   */
  exports.prototype['body'] = undefined;
  /**
   * @member {Date} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * @member {module:model/UserEmbed} created_by
   */
  exports.prototype['created_by'] = undefined;
  /**
   * @member {Date} updated_at
   */
  exports.prototype['updated_at'] = undefined;
  /**
   * @member {module:model/UserEmbed} updated_by
   */
  exports.prototype['updated_by'] = undefined;
  /**
   * @member {Date} publish_requested_at
   */
  exports.prototype['publish_requested_at'] = undefined;
  /**
   * @member {module:model/UserEmbed} publish_requested_by
   */
  exports.prototype['publish_requested_by'] = undefined;
  /**
   * @member {Date} published_start
   */
  exports.prototype['published_start'] = undefined;
  /**
   * @member {Date} published_end
   */
  exports.prototype['published_end'] = undefined;
  /**
   * @member {Date} launched_at
   */
  exports.prototype['launched_at'] = undefined;
  /**
   * @member {Array.<module:model/ImageEmbed>} images
   */
  exports.prototype['images'] = undefined;
  /**
   * @member {module:model/NutritionDeclarationEmbed} nutrition_declaration
   */
  exports.prototype['nutrition_declaration'] = undefined;
  /**
   * @member {Object} extended_attributes
   */
  exports.prototype['extended_attributes'] = undefined;



  return exports;
}));


