/**
 * podravka.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.2.3-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ImageEmbed', 'model/RecipeIngredientEmbed', 'model/RecipePreparationStepEmbed', 'model/UserEmbed', 'model/VideoEmbed'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ImageEmbed'), require('./RecipeIngredientEmbed'), require('./RecipePreparationStepEmbed'), require('./UserEmbed'), require('./VideoEmbed'));
  } else {
    // Browser globals (root is window)
    if (!root.Podravkaio) {
      root.Podravkaio = {};
    }
    root.Podravkaio.RecipeRead = factory(root.Podravkaio.ApiClient, root.Podravkaio.ImageEmbed, root.Podravkaio.RecipeIngredientEmbed, root.Podravkaio.RecipePreparationStepEmbed, root.Podravkaio.UserEmbed, root.Podravkaio.VideoEmbed);
  }
}(this, function(ApiClient, ImageEmbed, RecipeIngredientEmbed, RecipePreparationStepEmbed, UserEmbed, VideoEmbed) {
  'use strict';




  /**
   * The RecipeRead model module.
   * @module model/RecipeRead
   * @version 0.2.0
   */

  /**
   * Constructs a new <code>RecipeRead</code>.
   * Recipe.
   * @alias module:model/RecipeRead
   * @class
   */
  var exports = function() {
    var _this = this;


























  };

  /**
   * Constructs a <code>RecipeRead</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RecipeRead} obj Optional instance to populate.
   * @return {module:model/RecipeRead} The populated <code>RecipeRead</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('slug')) {
        obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
      }
      if (data.hasOwnProperty('lead')) {
        obj['lead'] = ApiClient.convertToType(data['lead'], 'String');
      }
      if (data.hasOwnProperty('advice')) {
        obj['advice'] = ApiClient.convertToType(data['advice'], 'String');
      }
      if (data.hasOwnProperty('secret')) {
        obj['secret'] = ApiClient.convertToType(data['secret'], 'String');
      }
      if (data.hasOwnProperty('remark')) {
        obj['remark'] = ApiClient.convertToType(data['remark'], 'String');
      }
      if (data.hasOwnProperty('serving')) {
        obj['serving'] = ApiClient.convertToType(data['serving'], 'String');
      }
      if (data.hasOwnProperty('author')) {
        obj['author'] = UserEmbed.constructFromObject(data['author']);
      }
      if (data.hasOwnProperty('image')) {
        obj['image'] = ImageEmbed.constructFromObject(data['image']);
      }
      if (data.hasOwnProperty('images')) {
        obj['images'] = ApiClient.convertToType(data['images'], [ImageEmbed]);
      }
      if (data.hasOwnProperty('video')) {
        obj['video'] = VideoEmbed.constructFromObject(data['video']);
      }
      if (data.hasOwnProperty('videos')) {
        obj['videos'] = ApiClient.convertToType(data['videos'], [VideoEmbed]);
      }
      if (data.hasOwnProperty('ingredients')) {
        obj['ingredients'] = ApiClient.convertToType(data['ingredients'], [RecipeIngredientEmbed]);
      }
      if (data.hasOwnProperty('preparation_steps')) {
        obj['preparation_steps'] = ApiClient.convertToType(data['preparation_steps'], [RecipePreparationStepEmbed]);
      }
      if (data.hasOwnProperty('published_start')) {
        obj['published_start'] = ApiClient.convertToType(data['published_start'], 'Date');
      }
      if (data.hasOwnProperty('published_end')) {
        obj['published_end'] = ApiClient.convertToType(data['published_end'], 'Date');
      }
      if (data.hasOwnProperty('published')) {
        obj['published'] = ApiClient.convertToType(data['published'], 'Boolean');
      }
      if (data.hasOwnProperty('owned_by')) {
        obj['owned_by'] = UserEmbed.constructFromObject(data['owned_by']);
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
      }
      if (data.hasOwnProperty('created_by')) {
        obj['created_by'] = UserEmbed.constructFromObject(data['created_by']);
      }
      if (data.hasOwnProperty('updated_at')) {
        obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
      }
      if (data.hasOwnProperty('updated_by')) {
        obj['updated_by'] = UserEmbed.constructFromObject(data['updated_by']);
      }
      if (data.hasOwnProperty('state')) {
        obj['state'] = ApiClient.convertToType(data['state'], 'String');
      }
      if (data.hasOwnProperty('extended_attributes')) {
        obj['extended_attributes'] = ApiClient.convertToType(data['extended_attributes'], Object);
      }
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * @member {String} slug
   */
  exports.prototype['slug'] = undefined;
  /**
   * @member {String} lead
   */
  exports.prototype['lead'] = undefined;
  /**
   * @member {String} advice
   */
  exports.prototype['advice'] = undefined;
  /**
   * @member {String} secret
   */
  exports.prototype['secret'] = undefined;
  /**
   * @member {String} remark
   */
  exports.prototype['remark'] = undefined;
  /**
   * @member {String} serving
   */
  exports.prototype['serving'] = undefined;
  /**
   * @member {module:model/UserEmbed} author
   */
  exports.prototype['author'] = undefined;
  /**
   * @member {module:model/ImageEmbed} image
   */
  exports.prototype['image'] = undefined;
  /**
   * @member {Array.<module:model/ImageEmbed>} images
   */
  exports.prototype['images'] = undefined;
  /**
   * @member {module:model/VideoEmbed} video
   */
  exports.prototype['video'] = undefined;
  /**
   * @member {Array.<module:model/VideoEmbed>} videos
   */
  exports.prototype['videos'] = undefined;
  /**
   * @member {Array.<module:model/RecipeIngredientEmbed>} ingredients
   */
  exports.prototype['ingredients'] = undefined;
  /**
   * @member {Array.<module:model/RecipePreparationStepEmbed>} preparation_steps
   */
  exports.prototype['preparation_steps'] = undefined;
  /**
   * @member {Date} published_start
   */
  exports.prototype['published_start'] = undefined;
  /**
   * @member {Date} published_end
   */
  exports.prototype['published_end'] = undefined;
  /**
   * @member {Boolean} published
   */
  exports.prototype['published'] = undefined;
  /**
   * @member {module:model/UserEmbed} owned_by
   */
  exports.prototype['owned_by'] = undefined;
  /**
   * @member {Date} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * @member {module:model/UserEmbed} created_by
   */
  exports.prototype['created_by'] = undefined;
  /**
   * @member {Date} updated_at
   */
  exports.prototype['updated_at'] = undefined;
  /**
   * @member {module:model/UserEmbed} updated_by
   */
  exports.prototype['updated_by'] = undefined;
  /**
   * @member {String} state
   */
  exports.prototype['state'] = undefined;
  /**
   * @member {Object} extended_attributes
   */
  exports.prototype['extended_attributes'] = undefined;



  return exports;
}));


