/**
 * podravka.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.2.3-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Podravkaio) {
      root.Podravkaio = {};
    }
    root.Podravkaio.User = factory(root.Podravkaio.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The User model module.
   * @module model/User
   * @version 0.2.0
   */

  /**
   * Constructs a new <code>User</code>.
   * Class User.
   * @alias module:model/User
   * @class
   */
  var exports = function() {
    var _this = this;
















  };

  /**
   * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/User} obj Optional instance to populate.
   * @return {module:model/User} The populated <code>User</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('display_name')) {
        obj['display_name'] = ApiClient.convertToType(data['display_name'], 'String');
      }
      if (data.hasOwnProperty('public_url')) {
        obj['public_url'] = ApiClient.convertToType(data['public_url'], 'String');
      }
      if (data.hasOwnProperty('avatar')) {
        obj['avatar'] = ApiClient.convertToType(data['avatar'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('account')) {
        obj['account'] = ApiClient.convertToType(data['account'], 'String');
      }
      if (data.hasOwnProperty('owned_by_client')) {
        obj['owned_by_client'] = ApiClient.convertToType(data['owned_by_client'], 'String');
      }
      if (data.hasOwnProperty('grants')) {
        obj['grants'] = ApiClient.convertToType(data['grants'], ['String']);
      }
      if (data.hasOwnProperty('new')) {
        obj['new'] = ApiClient.convertToType(data['new'], 'Boolean');
      }
      if (data.hasOwnProperty('extended_attributes')) {
        obj['extended_attributes'] = ApiClient.convertToType(data['extended_attributes'], 'String');
      }
      if (data.hasOwnProperty('extended_attribute')) {
        obj['extended_attribute'] = ApiClient.convertToType(data['extended_attribute'], 'String');
      }
      if (data.hasOwnProperty('owned_by_user')) {
        obj['owned_by_user'] = ApiClient.convertToType(data['owned_by_user'], 'String');
      }
      if (data.hasOwnProperty('owned_by_user_profile')) {
        obj['owned_by_user_profile'] = ApiClient.convertToType(data['owned_by_user_profile'], 'String');
      }
      if (data.hasOwnProperty('owned_by')) {
        obj['owned_by'] = ApiClient.convertToType(data['owned_by'], 'String');
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
      }
      if (data.hasOwnProperty('updated_at')) {
        obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
      }
    }
    return obj;
  }

  /**
   * @member {String} display_name
   */
  exports.prototype['display_name'] = undefined;
  /**
   * @member {String} public_url
   */
  exports.prototype['public_url'] = undefined;
  /**
   * @member {String} avatar
   */
  exports.prototype['avatar'] = undefined;
  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} account
   */
  exports.prototype['account'] = undefined;
  /**
   * @member {String} owned_by_client
   */
  exports.prototype['owned_by_client'] = undefined;
  /**
   * @member {Array.<String>} grants
   */
  exports.prototype['grants'] = undefined;
  /**
   * @member {Boolean} new
   */
  exports.prototype['new'] = undefined;
  /**
   * @member {String} extended_attributes
   */
  exports.prototype['extended_attributes'] = undefined;
  /**
   * @member {String} extended_attribute
   */
  exports.prototype['extended_attribute'] = undefined;
  /**
   * @member {String} owned_by_user
   */
  exports.prototype['owned_by_user'] = undefined;
  /**
   * @member {String} owned_by_user_profile
   */
  exports.prototype['owned_by_user_profile'] = undefined;
  /**
   * @member {String} owned_by
   */
  exports.prototype['owned_by'] = undefined;
  /**
   * @member {Date} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * @member {Date} updated_at
   */
  exports.prototype['updated_at'] = undefined;



  return exports;
}));


