/**
 * podravka.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.2.3-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/VideoOriginCreate'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./VideoOriginCreate'));
  } else {
    // Browser globals (root is window)
    if (!root.Podravkaio) {
      root.Podravkaio = {};
    }
    root.Podravkaio.VideoCreate = factory(root.Podravkaio.ApiClient, root.Podravkaio.VideoOriginCreate);
  }
}(this, function(ApiClient, VideoOriginCreate) {
  'use strict';




  /**
   * The VideoCreate model module.
   * @module model/VideoCreate
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>VideoCreate</code>.
   * Video.
   * @alias module:model/VideoCreate
   * @class
   * @param name {String} 
   */
  var exports = function(name) {
    var _this = this;

    _this['name'] = name;


  };

  /**
   * Constructs a <code>VideoCreate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VideoCreate} obj Optional instance to populate.
   * @return {module:model/VideoCreate} The populated <code>VideoCreate</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('custom_thumbnail')) {
        obj['custom_thumbnail'] = ApiClient.convertToType(data['custom_thumbnail'], 'String');
      }
      if (data.hasOwnProperty('origin')) {
        obj['origin'] = VideoOriginCreate.constructFromObject(data['origin']);
      }
    }
    return obj;
  }

  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} custom_thumbnail
   */
  exports.prototype['custom_thumbnail'] = undefined;
  /**
   * @member {module:model/VideoOriginCreate} origin
   */
  exports.prototype['origin'] = undefined;



  return exports;
}));


