/**
 * podravka.io
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Podravkaio);
  }
}(this, function(expect, Podravkaio) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Podravkaio.ArticleArticleUpdate();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ArticleArticleUpdate', function() {
    it('should create an instance of ArticleArticleUpdate', function() {
      // uncomment below and update the code to test ArticleArticleUpdate
      //var instane = new Podravkaio.ArticleArticleUpdate();
      //expect(instance).to.be.a(Podravkaio.ArticleArticleUpdate);
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instane = new Podravkaio.ArticleArticleUpdate();
      //expect(instance).to.be();
    });

    it('should have the property image (base name: "image")', function() {
      // uncomment below and update the code to test the property image
      //var instane = new Podravkaio.ArticleArticleUpdate();
      //expect(instance).to.be();
    });

    it('should have the property subtitle (base name: "subtitle")', function() {
      // uncomment below and update the code to test the property subtitle
      //var instane = new Podravkaio.ArticleArticleUpdate();
      //expect(instance).to.be();
    });

    it('should have the property teaser (base name: "teaser")', function() {
      // uncomment below and update the code to test the property teaser
      //var instane = new Podravkaio.ArticleArticleUpdate();
      //expect(instance).to.be();
    });

    it('should have the property location (base name: "location")', function() {
      // uncomment below and update the code to test the property location
      //var instane = new Podravkaio.ArticleArticleUpdate();
      //expect(instance).to.be();
    });

    it('should have the property lead (base name: "lead")', function() {
      // uncomment below and update the code to test the property lead
      //var instane = new Podravkaio.ArticleArticleUpdate();
      //expect(instance).to.be();
    });

    it('should have the property body (base name: "body")', function() {
      // uncomment below and update the code to test the property body
      //var instane = new Podravkaio.ArticleArticleUpdate();
      //expect(instance).to.be();
    });

    it('should have the property publishedStart (base name: "published_start")', function() {
      // uncomment below and update the code to test the property publishedStart
      //var instane = new Podravkaio.ArticleArticleUpdate();
      //expect(instance).to.be();
    });

    it('should have the property publishedEnd (base name: "published_end")', function() {
      // uncomment below and update the code to test the property publishedEnd
      //var instane = new Podravkaio.ArticleArticleUpdate();
      //expect(instance).to.be();
    });

    it('should have the property author (base name: "author")', function() {
      // uncomment below and update the code to test the property author
      //var instane = new Podravkaio.ArticleArticleUpdate();
      //expect(instance).to.be();
    });

    it('should have the property images (base name: "images")', function() {
      // uncomment below and update the code to test the property images
      //var instane = new Podravkaio.ArticleArticleUpdate();
      //expect(instance).to.be();
    });

    it('should have the property origin (base name: "origin")', function() {
      // uncomment below and update the code to test the property origin
      //var instane = new Podravkaio.ArticleArticleUpdate();
      //expect(instance).to.be();
    });

  });

}));
