/**
 * podravka.io
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ImageImageCreate', 'model/ImageImageCreateReadRead', 'model/ImageImageListList', 'model/ImageImageReadRead', 'model/ImageImageUpdate', 'model/ImageImageUpdateReadUpdateReadRead', 'model/ImageInstanceImageRead', 'model/ImageOriginImageCreate', 'model/ImageVariationImageRead', 'model/ImageVariationUrlVarsImageRead', 'model/UserImageCreateReadReadList', 'api/ImageApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/ImageImageCreate'), require('./model/ImageImageCreateReadRead'), require('./model/ImageImageListList'), require('./model/ImageImageReadRead'), require('./model/ImageImageUpdate'), require('./model/ImageImageUpdateReadUpdateReadRead'), require('./model/ImageInstanceImageRead'), require('./model/ImageOriginImageCreate'), require('./model/ImageVariationImageRead'), require('./model/ImageVariationUrlVarsImageRead'), require('./model/UserImageCreateReadReadList'), require('./api/ImageApi'));
  }
}(function(ApiClient, ImageImageCreate, ImageImageCreateReadRead, ImageImageListList, ImageImageReadRead, ImageImageUpdate, ImageImageUpdateReadUpdateReadRead, ImageInstanceImageRead, ImageOriginImageCreate, ImageVariationImageRead, ImageVariationUrlVarsImageRead, UserImageCreateReadReadList, ImageApi) {
  'use strict';

  /**
   * ERROR_UNKNOWN.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var Podravkaio = require('index'); // See note below*.
   * var xxxSvc = new Podravkaio.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new Podravkaio.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new Podravkaio.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new Podravkaio.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 0.0.1
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The ImageImageCreate model constructor.
     * @property {module:model/ImageImageCreate}
     */
    ImageImageCreate: ImageImageCreate,
    /**
     * The ImageImageCreateReadRead model constructor.
     * @property {module:model/ImageImageCreateReadRead}
     */
    ImageImageCreateReadRead: ImageImageCreateReadRead,
    /**
     * The ImageImageListList model constructor.
     * @property {module:model/ImageImageListList}
     */
    ImageImageListList: ImageImageListList,
    /**
     * The ImageImageReadRead model constructor.
     * @property {module:model/ImageImageReadRead}
     */
    ImageImageReadRead: ImageImageReadRead,
    /**
     * The ImageImageUpdate model constructor.
     * @property {module:model/ImageImageUpdate}
     */
    ImageImageUpdate: ImageImageUpdate,
    /**
     * The ImageImageUpdateReadUpdateReadRead model constructor.
     * @property {module:model/ImageImageUpdateReadUpdateReadRead}
     */
    ImageImageUpdateReadUpdateReadRead: ImageImageUpdateReadUpdateReadRead,
    /**
     * The ImageInstanceImageRead model constructor.
     * @property {module:model/ImageInstanceImageRead}
     */
    ImageInstanceImageRead: ImageInstanceImageRead,
    /**
     * The ImageOriginImageCreate model constructor.
     * @property {module:model/ImageOriginImageCreate}
     */
    ImageOriginImageCreate: ImageOriginImageCreate,
    /**
     * The ImageVariationImageRead model constructor.
     * @property {module:model/ImageVariationImageRead}
     */
    ImageVariationImageRead: ImageVariationImageRead,
    /**
     * The ImageVariationUrlVarsImageRead model constructor.
     * @property {module:model/ImageVariationUrlVarsImageRead}
     */
    ImageVariationUrlVarsImageRead: ImageVariationUrlVarsImageRead,
    /**
     * The UserImageCreateReadReadList model constructor.
     * @property {module:model/UserImageCreateReadReadList}
     */
    UserImageCreateReadReadList: UserImageCreateReadReadList,
    /**
     * The ImageApi service constructor.
     * @property {module:api/ImageApi}
     */
    ImageApi: ImageApi
  };

  return exports;
}));
