/**
 * podravka.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.2.3-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Podravkaio);
  }
}(this, function(expect, Podravkaio) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Podravkaio.IngredientApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('IngredientApi', function() {
    describe('createIngredient', function() {
      it('should call createIngredient successfully', function(done) {
        //uncomment below and update the code to test createIngredient
        //instance.createIngredient(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteIngredient', function() {
      it('should call deleteIngredient successfully', function(done) {
        //uncomment below and update the code to test deleteIngredient
        //instance.deleteIngredient(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getIngredient', function() {
      it('should call getIngredient successfully', function(done) {
        //uncomment below and update the code to test getIngredient
        //instance.getIngredient(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getIngredientList', function() {
      it('should call getIngredientList successfully', function(done) {
        //uncomment below and update the code to test getIngredientList
        //instance.getIngredientList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getIngredientState', function() {
      it('should call getIngredientState successfully', function(done) {
        //uncomment below and update the code to test getIngredientState
        //instance.getIngredientState(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setIngredientState', function() {
      it('should call setIngredientState successfully', function(done) {
        //uncomment below and update the code to test setIngredientState
        //instance.setIngredientState(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateIngredient', function() {
      it('should call updateIngredient successfully', function(done) {
        //uncomment below and update the code to test updateIngredient
        //instance.updateIngredient(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
