/**
 * podravka.io
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ImageImageUpdateReadUpdateReadRead model module.
* @module model/ImageImageUpdateReadUpdateReadRead
* @version 0.0.1
*/
export default class ImageImageUpdateReadUpdateReadRead {
    /**
    * Constructs a new <code>ImageImageUpdateReadUpdateReadRead</code>.
    * Image.
    * @alias module:model/ImageImageUpdateReadUpdateReadRead
    * @class
    * @param name {String} 
    */

    constructor(name) {
        

        
        

        this['name'] = name;

        
    }

    /**
    * Constructs a <code>ImageImageUpdateReadUpdateReadRead</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ImageImageUpdateReadUpdateReadRead} obj Optional instance to populate.
    * @return {module:model/ImageImageUpdateReadUpdateReadRead} The populated <code>ImageImageUpdateReadUpdateReadRead</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ImageImageUpdateReadUpdateReadRead();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {String} state
    */
    state = undefined;
    /**
    * @member {String} name
    */
    name = undefined;








}


