/**
 * podravka.io
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ImageImageCreate model module.
* @module model/ImageImageCreate
* @version 0.0.1
*/
export default class ImageImageCreate {
    /**
    * Constructs a new <code>ImageImageCreate</code>.
    * Image.
    * @alias module:model/ImageImageCreate
    * @class
    * @param name {String} 
    */

    constructor(name) {
        

        
        

        this['name'] = name;

        
    }

    /**
    * Constructs a <code>ImageImageCreate</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ImageImageCreate} obj Optional instance to populate.
    * @return {module:model/ImageImageCreate} The populated <code>ImageImageCreate</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ImageImageCreate();

            
            
            

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('origin')) {
                obj['origin'] = ApiClient.convertToType(data['origin'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} origin
    */
    origin = undefined;








}


